# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Rudrigo\Desktop\SENFIO\designer\tela_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormServer(object):
    def setupUi(self, FormServer):
        FormServer.setObjectName("FormServer")
        FormServer.resize(650, 518)
        FormServer.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.verticalLayout = QtWidgets.QVBoxLayout(FormServer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FormServer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(274, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(274, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(FormServer)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_6 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.groupBox)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEditServer = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditServer.setObjectName("lineEditServer")
        self.verticalLayout_4.addWidget(self.lineEditServer)
        self.lineEditPort = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditPort.setObjectName("lineEditPort")
        self.verticalLayout_4.addWidget(self.lineEditPort)
        self.lineEditQos = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditQos.setObjectName("lineEditQos")
        self.verticalLayout_4.addWidget(self.lineEditQos)
        self.lineEditUser = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditUser.setObjectName("lineEditUser")
        self.verticalLayout_4.addWidget(self.lineEditUser)
        self.lineEditPasswd = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditPasswd.setObjectName("lineEditPasswd")
        self.verticalLayout_4.addWidget(self.lineEditPasswd)
        self.lineEditTpub = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditTpub.setObjectName("lineEditTpub")
        self.verticalLayout_4.addWidget(self.lineEditTpub)
        self.lineEditTsub = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditTsub.setObjectName("lineEditTsub")
        self.verticalLayout_4.addWidget(self.lineEditTsub)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(FormServer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btnSairServer = QtWidgets.QPushButton(self.frame_4)
        self.btnSairServer.setMinimumSize(QtCore.QSize(100, 50))
        self.btnSairServer.setStyleSheet("QPushButton {\n"
"     color: white;\n"
"     font: bold 12pt;\n"
"     background-color: #379ca8;\n"
"     border: 1px solid black;\n"
"     border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0             rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}")
        self.btnSairServer.setObjectName("btnSairServer")
        self.horizontalLayout_4.addWidget(self.btnSairServer)
        self.btnSalvarServer = QtWidgets.QPushButton(self.frame_4)
        self.btnSalvarServer.setMinimumSize(QtCore.QSize(100, 50))
        self.btnSalvarServer.setStyleSheet("QPushButton {\n"
"     color: white;\n"
"     font: bold 12pt;\n"
"     background-color: #379ca8;\n"
"     border: 1px solid black;\n"
"     border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0             rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}")
        self.btnSalvarServer.setObjectName("btnSalvarServer")
        self.horizontalLayout_4.addWidget(self.btnSalvarServer)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame_4)

        self.retranslateUi(FormServer)
        self.btnSairServer.clicked.connect(FormServer.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FormServer)

    def retranslateUi(self, FormServer):
        _translate = QtCore.QCoreApplication.translate
        FormServer.setWindowTitle(_translate("FormServer", "Servidor"))
        self.label.setText(_translate("FormServer", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Servidor</span></p></body></html>"))
        self.label_3.setText(_translate("FormServer", "Servidor:"))
        self.label_4.setText(_translate("FormServer", "Porta:"))
        self.label_2.setText(_translate("FormServer", "QoS:"))
        self.label_5.setText(_translate("FormServer", "Usuário:"))
        self.label_6.setText(_translate("FormServer", "Senha:"))
        self.label_7.setText(_translate("FormServer", "Tópico PUB:"))
        self.label_8.setText(_translate("FormServer", "Tópico SUB:"))
        self.btnSairServer.setText(_translate("FormServer", "Sair"))
        self.btnSalvarServer.setText(_translate("FormServer", "Salvar"))
