# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Rudrigo\Desktop\SENFIO_V1.2\designer\tela_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormConfig(object):
    def setupUi(self, FormConfig):
        FormConfig.setObjectName("FormConfig")
        FormConfig.resize(650, 518)
        FormConfig.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.verticalLayout = QtWidgets.QVBoxLayout(FormConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FormConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(274, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(274, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(FormConfig)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBoxS1 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBoxS1.setGeometry(QtCore.QRect(10, 70, 121, 22))
        self.comboBoxS1.setObjectName("comboBoxS1")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 55, 16))
        self.label_2.setObjectName("label_2")
        self.comboBoxBaud1 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBoxBaud1.setGeometry(QtCore.QRect(10, 150, 121, 22))
        self.comboBoxBaud1.setObjectName("comboBoxBaud1")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.label_3.setObjectName("label_3")
        self.checkBoxS1 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxS1.setGeometry(QtCore.QRect(30, 210, 81, 51))
        self.checkBoxS1.setText("")
        self.checkBoxS1.setObjectName("checkBoxS1")
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBoxS2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxS2.setGeometry(QtCore.QRect(10, 70, 121, 22))
        self.comboBoxS2.setObjectName("comboBoxS2")
        self.comboBoxBaud2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxBaud2.setGeometry(QtCore.QRect(10, 150, 121, 22))
        self.comboBoxBaud2.setObjectName("comboBoxBaud2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 55, 16))
        self.label_7.setObjectName("label_7")
        self.checkBoxS2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxS2.setGeometry(QtCore.QRect(30, 210, 81, 51))
        self.checkBoxS2.setText("")
        self.checkBoxS2.setObjectName("checkBoxS2")
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBoxS3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxS3.setGeometry(QtCore.QRect(10, 70, 121, 22))
        self.comboBoxS3.setObjectName("comboBoxS3")
        self.comboBoxBaud3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxBaud3.setGeometry(QtCore.QRect(10, 150, 121, 22))
        self.comboBoxBaud3.setObjectName("comboBoxBaud3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 55, 16))
        self.label_8.setObjectName("label_8")
        self.checkBoxS3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxS3.setGeometry(QtCore.QRect(30, 210, 81, 51))
        self.checkBoxS3.setText("")
        self.checkBoxS3.setObjectName("checkBoxS3")
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.comboBoxS4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxS4.setGeometry(QtCore.QRect(10, 70, 121, 20))
        self.comboBoxS4.setObjectName("comboBoxS4")
        self.comboBoxBaud4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxBaud4.setGeometry(QtCore.QRect(10, 150, 121, 22))
        self.comboBoxBaud4.setObjectName("comboBoxBaud4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 121, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 55, 16))
        self.label_9.setObjectName("label_9")
        self.checkBoxS4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxS4.setGeometry(QtCore.QRect(30, 210, 81, 51))
        self.checkBoxS4.setText("")
        self.checkBoxS4.setObjectName("checkBoxS4")
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(FormConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSairConfig = QtWidgets.QPushButton(self.frame_4)
        self.btnSairConfig.setMinimumSize(QtCore.QSize(100, 50))
        self.btnSairConfig.setStyleSheet("QPushButton {\n"
"     color: white;\n"
"     font: bold 12pt;\n"
"     background-color: #379ca8;\n"
"     border: 1px solid black;\n"
"     border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0             rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}")
        self.btnSairConfig.setObjectName("btnSairConfig")
        self.horizontalLayout_4.addWidget(self.btnSairConfig)
        self.btnAtualizaConfig = QtWidgets.QPushButton(self.frame_4)
        self.btnAtualizaConfig.setMinimumSize(QtCore.QSize(100, 50))
        self.btnAtualizaConfig.setStyleSheet("QPushButton {\n"
"     color: white;\n"
"     font: bold 12pt;\n"
"     background-color: #379ca8;\n"
"     border: 1px solid black;\n"
"     border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0             rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}")
        self.btnAtualizaConfig.setObjectName("btnAtualizaConfig")
        self.horizontalLayout_4.addWidget(self.btnAtualizaConfig)
        self.btnSalvarConfig = QtWidgets.QPushButton(self.frame_4)
        self.btnSalvarConfig.setMinimumSize(QtCore.QSize(100, 50))
        self.btnSalvarConfig.setStyleSheet("QPushButton {\n"
"     color: white;\n"
"     font: bold 12pt;\n"
"     background-color: #379ca8;\n"
"     border: 1px solid black;\n"
"     border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0             rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}")
        self.btnSalvarConfig.setObjectName("btnSalvarConfig")
        self.horizontalLayout_4.addWidget(self.btnSalvarConfig)
        self.verticalLayout.addWidget(self.frame_4)

        self.retranslateUi(FormConfig)
        self.btnSairConfig.clicked.connect(FormConfig.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FormConfig)

    def retranslateUi(self, FormConfig):
        _translate = QtCore.QCoreApplication.translate
        FormConfig.setWindowTitle(_translate("FormConfig", "Configuração"))
        self.label.setText(_translate("FormConfig", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Configuração Serial</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("FormConfig", "Serial 1 -> Placa 1"))
        self.label_2.setText(_translate("FormConfig", "Serial"))
        self.label_3.setText(_translate("FormConfig", "BaudRate"))
        self.groupBox_3.setTitle(_translate("FormConfig", "Serial 2 -> Placa 2"))
        self.label_4.setText(_translate("FormConfig", "BaudRate"))
        self.label_7.setText(_translate("FormConfig", "Serial"))
        self.groupBox_2.setTitle(_translate("FormConfig", "Serial 3 -> Placa 3"))
        self.label_5.setText(_translate("FormConfig", "BaudRate"))
        self.label_8.setText(_translate("FormConfig", "Serial"))
        self.groupBox.setTitle(_translate("FormConfig", "Serial 4 -> Placa 4"))
        self.label_6.setText(_translate("FormConfig", "BaudRate"))
        self.label_9.setText(_translate("FormConfig", "Serial"))
        self.btnSairConfig.setText(_translate("FormConfig", "Sair"))
        self.btnAtualizaConfig.setText(_translate("FormConfig", "Atualizar"))
        self.btnSalvarConfig.setText(_translate("FormConfig", "Salvar"))
